CREATE TABLE CLIENT (
    ID      INT             NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    NAME    VARCHAR(100)    NOT NULL
);

CREATE TABLE PAYACCOUNT (
    ID          INT             NOT NULL    AUTO_INCREMENT      PRIMARY KEY,
    DATE        DATE            NOT NULL,
    DATE_EXP  DATE            NOT NULL,
    IDCLIENT    INT,
    VALUE       DECIMAL(12, 2)
);

ALTER TABLE PAYACCOUNT ADD CONSTRAINT FK_PAYACCOUNT_CLIENT FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(ID);

INSERT INTO CLIENT(NAME) VALUES ("Richard");
INSERT INTO PAYACCOUNT(DATE, DATE_EXP, IDCLIENT, VALUE) VALUES ("2006/03/18", "2006/04/18", 1, 166.50);

